### ISSUE TITLE
Automatically generate documentation for inclusion in manual

### ISSUE THREAD

**Issue by tomfrancart** [exporl/apex3#122]
https://trello.com/c/0cZz296x/86-automatically-generate-documentation-for-inclusion-in-manual

**Comment by tomfrancart** [comment]
Most important is to include the documentation for the different APIs, extracted (doxygen) from the source code

**Comment by Gundersanne** [comment]
The script to do this exists. 

generate docs, push to https://github.com/exporl/apex3-documentation-schemas, update apex3-doc.

It's more how often do we want to do this. I thought every master build seemed a bit silly. But maybe we can do something where it'll run the script each time something in the data/schemas directory changed?

**Comment by tomfrancart** [comment]
or on public releases = when the schema version number changes ?

**Comment by Gundersanne** [comment]
Ah yea that's best, I think i forgot to upgrade them to 3.1.5 anyway, i'll include it in the new-version script.
