### ISSUE TITLE
Add HTML/javascript support for flowrunner and resultsviewer

### ISSUE THREAD

**Issue by tomfrancart** [exporl/apex3#162]
https://trello.com/c/sE1mxptL/135-add-html-javascript-support-for-flowrunner-and-resultsviewer

**Comment by Gundersanne** [comment]
Hmm the trello ticket isn't available anymore.

So the flowrunner we have now.

Should the resultsviewer be available on tablet as well? It's definitely a good idea to switch the resultsviewer over to the common webview.

**Comment by tomfrancart** [comment]
I agree that the resultsviewer should be switched over to the common webview, and when we do that, it will probably be available on tablet as well?
we don't need it urgently on tablet, but will need it in the future
