### ISSUE TITLE
Show output from Coh helper program in console

### ISSUE THREAD

**Issue by tomfrancart** [exporl/apex3#166]
- Please add documentation on how to debug to manual: documentation/manual/l34device.tex

- If not too difficult, add unit test that loads Coh/NIC3 and plays a stimulus

**Comment by mh21** [comment]
No documentation added, but debug output in console window with gerrit #1881. There are unit tests for this in coh/tests/coh/...

**Comment by Gundersanne** [comment]
I could add some documentation still.

It's mostly putting verbose in the device configuration right?

**Comment by mh21** [comment]
yes I enabled that by default for now until all the weirdness is solved.

**Comment by tomfrancart** [comment]
@Gundersanne, it would be nice to document the interaction between the different modules a little bit (APEX - RPC - Python - NIC), and explain that parameters can be changed in apexconfig or inline in <device>
