### ISSUE TITLE
Convert latex documentation to Markdown, publish online

### ISSUE THREAD

**Issue by tomfrancart** [exporl/apex3#167]
Use github submodule + github pages

**Comment by Gundersanne** [comment]
Could we make a repository on github for this?

https://help.github.com/articles/creating-a-github-pages-site-with-the-jekyll-theme-chooser/ Jekyll + pages => edit markdown online and show in html.

**Comment by mh21** [comment]
You can just create it yourself :-) - apex3-documentation?

**Comment by Gundersanne** [comment]
Hmm, do we want the documentation on there or just the manual?

**Comment by mh21** [comment]
I think everything that is useful to understand how apex works

**Comment by Gundersanne** [comment]
are the reference manuals only available in pdf? 

And can I just publish the apexpaper (in pdf) there?
