### ISSUE TITLE
Schema validation errors

### ISSUE THREAD

**Issue by tomfrancart** [exporl/apex3#172]
when opening an experiment file and schema validation fails, the error messages is shown with HTML tags in it in the message window, e.g., :
<html xmlns='http://www.w3.org/1999/xhtml/'><body><p>Element <span class='XQuery-keyword'>answer</span> is not defined in this scope.</p></body></html>

This causes people to not read the error message ;)

**Comment by tomfrancart** [comment]
@mh21  can this have to do with an upgrade you did to the xml parser?

**Comment by mh21** [comment]
should be fixed with gerrit review request #1878.
