### ISSUE TITLE
expressions given in flowrunner are not in resultfile

### ISSUE THREAD

**Issue by bdieudonne** [exporl/apex3#174]
The expressions that are given to an experiment in the flowrunner (api.runExperiment(file,expressions)) are nowhere saved in the apr resultfile. Suggestion is to put them within the interactive tag, or add a new tag within the general tag, specifically for flowrunner expressions.

**Comment by Gundersanne** [comment]
I wouldn't do it within the interactive tag, the expressions and interactive serve distinct purposes.

The latter suggestion would be better where we modify the experiment schema to allow for a tag, the content of which is simply copied to the results file.

Technically something like this is already possible with the results/resultsparameters tag, but of course it's not intended for this and results in possible interactions with the resultsviewer.

Note that the expressions cannot create new elements, you'd have to predefine elements in the experiment file within that custom tag.

**Comment by tomfrancart** [comment]
I think it makes sense to merge it with interactive results somehow, as it will be used in the same way. Therefore I'm in favour of either adding it to interactive, or adding an element to <general> with a very similar structure to interactive. 
It may be easiest to parse if it's actually integrated with interactive.

**Comment by Gundersanne** [comment]
Then the best way to do this is to also insert the expressions into the parameterdialogresults which are written to the results file. This would result in the expressions behaving as if there were interactive elements present in the experiment file.

**Comment by tomfrancart** [comment]
I think that's OK

**Comment by Gundersanne** [comment]
change 2611
