### ISSUE TITLE
Apexconfig

### ISSUE THREAD

**Issue by liendecruy** [exporl/apex3#175]
When I installed one of the most recent versions of Apex (2017-02-21_07-49) on a Windows computer, I wanted to add a prefix in the apexconfig for my stimuli. When I added the path to the apexconfig, located in the ExpORL folder, Apex didn't succeed to find my wav-files. However, when I put the path into Windows Explorer, the files were found. The problem is that Apex can not handle the prefix "file" in the path. So this has to be changed from "file:C:/Users/LienDecruy/wavfiles/" to "C:/Users/LienDecruy/wavfiles" for example.

**Comment by tomfrancart** [comment]
Upgrade function needs to remove the file: prefix
