### ISSUE TITLE
FIR filter

### ISSUE THREAD

**Issue by liendecruy** [exporl/apex3#176]
We would like to use a HRTF filter in our apex experiment. But when we open it when the new version of Apex (2017-02-21_07-49), we get the following error: "ApexControl: Number of channels differ: plugin has 1 channels, FIR filter 0". When a previous version of Apex (3.1.1, march 2016), we don't get this problem. I attached the corresponding apx-file to this issue.
[FIRfilter - Apex 02-2017.zip](https://github.com/exporl/apex3/files/833998/FIRfilter.-.Apex.02-2017.zip)

**Comment by tomfrancart** [comment]
Can you specify the commit (hexadecimal number found in the message window, second line, or help|about) of both APEX versions?

**Comment by liendecruy** [comment]
Apex v3.1 (cf26cc) - 29febr2016
Apex v3.1 (37a059) - 16febr2017

**Comment by Gundersanne** [comment]
The parameter name uri got updated to file.

So in the apx file (in the firfilter configuration) instead of:
```
<filter ...>
...
<parameter id="uri">hrtf_coefficients/HRTF_RoomAnechoic_angle${angle}.bin</parameter>
...
</filter>
```

it should be:

```
<filter ...>
...
<parameter id="file">hrtf_coefficients/HRTF_RoomAnechoic_angle${angle}.bin</parameter>
...
</filter>
```

in order to work.

Is this desired?

**Comment by liendecruy** [comment]
This worked! Thank you Sanne!
