### ISSUE TITLE
The back button on Qt for Android in the mainwindow

### ISSUE THREAD

**Issue by Gundersanne** [exporl/apex3#177]
The default on handling the back button in Qt is terminating the application. This seems clunky, the user could accidentally hit the back button and the running experiment would be gone.

[https://bugreports.qt.io/browse/QTBUG-29063](url)
[https://wiki.qt.io/Qt_for_Android_known_issues](url)

Now either we accept the back key event in the mainwindow and nothing happens (which results in a not-very-android-like behaviour); or instead of terminating the application we force to suspend it somehow.  Don't know if the latter is possible.

Note that this is only in the QMainWindow. The various dialogs, popups,… work fine since they accept the event and process it before it reaches QGuiApplicationPrivate::processKeyEvent (which quits the application) .

**Comment by mh21** [comment]
in ApexMainWindow::closeEvent, we unconditonally accept the close event. Maybe we should show a popup instead if an experiment is running?

**Comment by Gundersanne** [comment]
add it to c/1905 ?

**Comment by Gundersanne** [comment]
https://exporl.med.kuleuven.be/gerrit/#/c/1913
