### ISSUE TITLE
<b> markup for spin keywords fails

### ISSUE THREAD

**Issue by AlexanderDudek** [exporl/apex3#180]
_Als we de SPIN interface gebruiken om de LIST af te nemen, dan verschijnen de zinnen die de proefpersoon moet horen, zoals het hoort op het scherm. Enkel het aanduiden van de kernwoorden loopt een beetje verkeerd. Normaal staan deze in het vet, maar nu worden ze omringd door de code \<b> \</b>. Hoe kunnen we dit oplossen zodat het weer gewoon in het vet staat?_ 

I'm guessing element tags are somehow being filtered out of the xml text?

Could this have to do with [this fix](https://github.com/exporl/apex3/issues/172)? @mh21

**Comment by mh21** [comment]
fixed by gerrit #1964
