### ISSUE TITLE
resultsviewer: accents in names responses

### ISSUE THREAD

**Issue by SaraMagits** [exporl/apex3#183]
![screenshot_accents](https://cloud.githubusercontent.com/assets/25302730/25483785/954cc768-2b57-11e7-949a-2bbd2924118c.png)
When stimulus or response name have an accent (e.g. é), the resultsviewer shows this as Ã©

**Comment by AlexanderDudek** [comment]
- Has been fixed by forcing UTF-8 encoding on TextStream when loading resultsfile into resultsviewer
- Gerrit # 1989
