### ISSUE TITLE
resultsfile in apex on tablet

### ISSUE THREAD

**Issue by SaraMagits** [exporl/apex3#187]
Resultsfile does not open when transferred to computer.
I can open it in Notepad ++ and see the parameters but not the results of the trials. 
 [ILD_4000Hz_2AFC_goldenstandard-results-s17m09.zip](https://github.com/exporl/apex3/files/1007015/ILD_4000Hz_2AFC_goldenstandard-results-s17m09.zip)

@Gundersanne

**Comment by Gundersanne** [comment]
Fixed in change 2038
