### ISSUE TITLE
calibration profile in resultsfile

### ISSUE THREAD

**Issue by SaraMagits** [exporl/apex3#188]
Is it possible to add the calibration profile that was used in the resultsfile? 
Now it shows the cardgain but not the profile that was used: 

![image](https://cloud.githubusercontent.com/assets/25302730/26403162/8524651c-408d-11e7-9b3a-1f78e09bfd76.png)

**Comment by Gundersanne** [comment]
Included hardware setup and profile that was used. Gerrit change 2058.

Should I include any other parameter information (default/max/min values) ? Or available stimuli in the hardware setup? Or Sound level meter data?

**Comment by tomfrancart** [comment]
Hardware setup and profile are sufficient.
