### ISSUE TITLE
Make triggers in aseq files optional

### ISSUE THREAD

**Issue by tomfrancart** [exporl/apex3#189]

**Comment by mh21** [comment]
they are optional in aseq files, but the stim mapper in coh needs to know whether you want triggers or not :-)

I'm not sure special-casing the triggers is the right approach. atm, we can specify default phase width, phase gap and period in the default map, maybe a default trigger would be the correct approach to fill in missing trigger values?

**Comment by tomfrancart** [comment]
do you mean specify default trigger value in the map (experiment file), like is done now for phasewidth etc?

**Comment by mh21** [comment]
yeah I think that would be the most consistent approach; there we could also support something like "first" to send a trigger on the first pulse of each data block etc.

**Comment by Gundersanne** [comment]
So expand the cohmapper to map triggers as well?

**Comment by tomfrancart** [comment]
yes, and add a tag trigger to the experiment file
