### ISSUE TITLE
android versioning

### ISSUE THREAD

**Issue by Gundersanne** [exporl/apex3#198]
If we want to set up a proper fdroid repo, we'll have to start versioning our apks.

Fdroid depends on versioncode in the androidmanifest to distinguish between builds, we could use the apex build number on the master branch.

We could have 2 repos, a debug repo that follows the master branch. And (in future) a more formal repo with release builds which updates less frequently.

**Comment by tomfrancart** [comment]
does the version number need to be monotonically increasing? Otherwise we could use the commit hash.

**Comment by Gundersanne** [comment]
There are 2 numbers. Version number (which should be 3.1.4 atm) and version code, which is simply a number that determines which version is newer (higher == newer).

This has to be set in the manifest so we do need to find a way to generate those somehow and keep them in a central location. Or we could use the build number in jenkins, pass that as a parameter to the build script.

**Comment by mh21** [comment]
commit timestamp?
