### ISSUE TITLE
Pluginprocedure progressbar is broken

### ISSUE THREAD

**Issue by AlexanderDudek** [exporl/apex3#200]
Even when defining a progress function, the bar continues to show 0% throughout the procedure, but will exit correctly when all trials have been presented

**Comment by AlexanderDudek** [comment]
After further analysis it seems the progress mechanic is NOT broken.
- heartrainprocedure in pluginprocedures implements the function incorrectly by calculating a value between [0-1] instead of [0-100]

Solution:
- fix the example pluginprocedures
- add documentation stating that this value needs to be 0-100

**Comment by Gundersanne** [comment]
c/2504

documentation already exists https://exporl.github.io/apex3-documentation/scripting/ under progress states 0-100.
