### ISSUE TITLE
Resultsviewer webview window does not let the inspect panel come into focus

### ISSUE THREAD

**Issue by AlexanderDudek** [exporl/apex3#201]
- When right clicking the resultsviewer and then selecting > Inspect, the inspector panel is a pop-under and cannot be clicked into focus (can't interact with the content)
- probably because of the type of window that this viewer is based on
- this is needed for debugging the resultsviewer, seeing as how some javascript behavior changes from browser to qt webview
- current workaround is making a debug version of the .html page being shown, where you change all relative "apex:..." refs to absolute refs and debugging it in chrome (suboptimal, because it lacks the automatic xml parsing of apr files and, as said in previous point, behavior can be slightly different)

**Comment by Gundersanne** [comment]
Moved resultsviewer to common webview. Is now a QMainWindow and thus not modal.
