### ISSUE TITLE
Finish SPIN refactory

### ISSUE THREAD

**Issue by tomfrancart** [exporl/apex3#204]
cf https://exporl.med.kuleuven.be/gerrit/#/c/1004/
One experiment file per speech material, dynamically generate datablocks etc using xmlplugins

**Comment by Gundersanne** [comment]
So far I rebased this.

What has been done and was still has to happen exactly? How should this integrate with the existing spin dialog?

**Comment by Gundersanne** [comment]
I refactored it a little, wrote a test which compares most of the experimentdata generated from the expanded experiments (not certain elements which you'd expect to be different), and added a checkbox on the procedure page of the dialog indicating whether or not you want to generate the experiment as a pluginprocedure.

I think a next step is to decide if we want to throw away any functionality/possibilities in the dialog.

Then fix all remaining bugs we can find.

**Comment by Gundersanne** [comment]
merged in 1004

More work to be done on this issue or can we close it?

**Comment by mh21** [comment]
That's your chance to close it :-)

Op 26 okt. 2017 1:24 p.m. schreef "Sanne" <notifications@github.com>:
