### ISSUE TITLE
Regular expressions check for interactive

### ISSUE THREAD

**Issue by mh21** [exporl/apex3#206]
Additionally, for
- all example experiments that have an identifier in interactive
- the spin interface

set a regular expression that conforms to the format used at ExpORL.

**Comment by Gundersanne** [comment]
So like [A-Z]\.[A-Z]\. ?

**Comment by mh21** [comment]
https://exporl.med.kuleuven.be/web/index.php/Using_anonymous_identifiers

**Comment by Gundersanne** [comment]
c 2519(merged), 2585
