### ISSUE TITLE
APEX on tablet - calibration

### ISSUE THREAD

**Issue by SaraMagits** [exporl/apex3#209]
calibration panel changes input (e.g., -7) but output doesn't change (SLM indicates same level)

**Comment by Gundersanne** [comment]
I think with bertha the calibration dialog got overlooked. The parameter changes are not being relayed to the datablocksplugin.

Will fix this asap.

**Comment by Gundersanne** [comment]
change 2635

**Comment by Gundersanne** [comment]
change 2645
