### ISSUE TITLE
SPIN keywords not bold

### ISSUE THREAD

**Issue by TildeVanHirtum** [exporl/apex3#217]
The keywords for the LIST sentences for the SPIN experiments are not shown in bold. It shows: Het is < b >druk< /b > op de < b >straat</ b > (without the extra white space, that is just to show the issue).

**Comment by Gundersanne** [comment]
Thanks for reporting!

I'm having truoble recreating the issue. Could you paste the exact apex version? (Found under help>about).

**Comment by TildeVanHirtum** [comment]
APEX v3.1 (fde358) - Fri Apri20 13:00:05 2018 +0200.
If it is any help, with my previous version it worked just fine (APEX v3.1 (acfe67) - Thu Jan 14 19:28:41 2016 +0100) .

**Comment by Gundersanne** [comment]
Again I can't recreate it. The (sentence)screen element use a heuristic to determine whether or not the text is rich text (which understands `<b>`) or plain. If a `<b>` tag is present before the first linebreak, it'll interpret it as rich text.
So this should work:
```
<parameter>Het is <b>druk</b></parameter>
```
But this should not:
```
<parameter>Het 

is <b>druk</b></parameter>
```

Could you enclose the specific *.apx ( and *.js if present) file that you're opening?

**Comment by Gundersanne** [comment]
I generated it with a 2016 version, and it generates the sentences as `Het is &lt;b>druk&lt;/b>...` and the newer version doesn't parse html-escaped characters `&lt;` anymore, it can be straight up <b>.

So yes, generate with newer version :)
