### ISSUE TITLE
random crashes in testbench; why is the sleep necessary in dummysoundcard?

### ISSUE THREAD

**Issue by tomfrancart** [exporl/apex3#49]
https://trello.com/c/YtyForCv/147-random-crashes-in-testbench-why-is-the-sleep-necessary-in-dummysoundcard

**Comment by Gundersanne** [comment]
The 10ms sleeps seems to fix this. Have had very few crashes in the past months.

Furthermore the 10ms sleep seems to speed up the testbench at least 4-fold. I think with a 0ms interval it takes a lot longer for apex to signal the main thread to stop the sound processing, as this doesn't go via the event loop (waitableobject uses mutexes).
