### ISSUE TITLE
Flowrunner relative paths in windows

### ISSUE THREAD

**Issue by tomfrancart** [exporl/apex3#83]
https://trello.com/c/Qt4TIvKm/121-flowrunner-relative-paths-in-windows

Bij het uitvoeren van het voorbeeldje, kreeg ik volgende foutmelding wanneer ik het experiment met relatief pad probeerde op te starten:
https://dl.dropboxusercontent.com/u/3099146/temp/bug.png

**Comment by Gundersanne** [comment]
This has been fixed and the examples/flowrunner/runner.apf showcases all of the api functionality.
